Resources:
  TagsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: tag
          AttributeType: S
        - AttributeName: ideaId
          AttributeType: S
        - AttributeName: index
          AttributeType: N
      KeySchema:
        - AttributeName: tag
          KeyType: HASH
        - AttributeName: ideaId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      TableName: ${self:custom.tagsTableName}
      GlobalSecondaryIndexes:
        - IndexName: ideaTags
          KeySchema:
            - AttributeName: ideaId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: ideaTagsByIndex
          KeySchema:
            - AttributeName: ideaId
              KeyType: HASH
            - AttributeName: index
              KeyType: RANGE
          Projection:
            ProjectionType: ALL