Resources:
  LikesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: ideaId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: likedTime
          AttributeType: S
      KeySchema:
        - AttributeName: ideaId
          KeyType: HASH
        - AttributeName: userId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      TableName: ${self:custom.likesTableName}
      GlobalSecondaryIndexes:
        - IndexName: userLikes
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: userLikesByDate
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: likedTime
              KeyType: RANGE
          Projection:
            ProjectionType: ALL