LambdaDevelopmentLoggerFunctionRole:
  Type: AWS::IAM::Role
  Properties:
    RoleName: "Lambda-DevelopmentLoggerFunctionRole"
    AssumeRolePolicyDocument:
      Version: "2012-10-17"
      Statement:
        - Effect: Allow
          Principal:
            Service: "lambda.amazonaws.com"
          Action: "sts:AssumeRole"
    Policies:
      - PolicyName: "Lambda-DevelopmentLoggerFunctionRole-Policy"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Action:
                - "logs:CreateLogGroup"
                - "logs:CreateLogStream"
                - "logs:PutLogEvents"
                - "logs:DescribeLogStreams"
              Effect: Allow
              Resource:
                - "arn:aws:logs:*:*:*"