 Resources:
    AssetsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.bucketName} # Specify a new bucket name for client assets
#        CorsConfiguration:
#          CorsRules:
#            - AllowedHeaders:
#                - "*"
#              AllowedMethods:
#                - GET
#              AllowedOrigins:
#                - ${self:provider.allowedOrigin}
    AssetsBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: AssetsBucket
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            -
              Action:
                - s3:*
              Effect: Allow
              Resource:
                Fn::Join:
                  - ""
                  -
                    - "arn:aws:s3:::"
                    -
                      Ref: AssetsBucket
                    - "/*"
              Principal:
                Service: "s3.amazonaws.com"
